### PR TITLE
Update collection.rb

### PR DESCRIPTION
**Pull request by voodoologic**
having a string for a key feels like an improvement.

### CODE REVIEW

**Comment by hiromi2424** [comment]
@voodoologic What is a use case of that change?

**Comment by voodoologic** [comment]
The way the code is with out the PR, the keys of the hash is are a Semantic::Version object.  It's really hard to work with.  I just turned it into a string. It is in keeping with your documenation.

**Comment by voodoologic** [comment]
In my own fork, I skip the hash all together https://github.com/voodoologic/ruby-yarnlock/blob/master/lib/yarnlock/entry/collection.rb#L14
with an array of entries I can iterate over them faster because the data object is flatter.

**Comment by hiromi2424** [comment]
@voodoologic I cannot imagine a real use case from your comment.
In addition, it might be good to define a new method to iterate like:

```ruby
  def index_by_package
    each_with_object({}) do |entry, packages|
      packages[entry.package] ||= []
      packages[entry.package] << entry
    end
  end
```

**Comment by voodoologic** [comment]
I updated the PR with to reflect your comment.  I also added a line to the gitignore so I could ignore vim swap files. 
I didn't use the library as instructed on the readme.  Instead I was able to use @yarnpkg/lockfile in a separate process and output the json to a file.  
```
const fs = require('fs');
const lockfile = require('@yarnpkg/lockfile');

let file = fs.readFileSync('yarn.lock', 'utf8');
let json = lockfile.parse(file);

const prettyJson = JSON.stringify(json.object, null, "\t")
fs.writeFile('lockfile_output.json', prettyJson, err => console.log(err) );
```

I then did
```
json_string = File.read('lockfile_output.json')
yarn_hash = JSON.parse(json_string)
collection  = Yarnlock::Entry::Collection.parse(yarn_hash)
package_with_version = collection.package_with_versions
```
I had to do it that way because nvm and bash scripting made it too hard run the scripts with the lockfile module loaded.  But, that's a separate topic from this PR.  Maybe someone else who comes along will find that useful.

**Comment by hiromi2424** [comment]
@voodoologic
I reject your work to this public repository due to:

- DO NOT break changes without enough discussion
- NEEDS test
- NEEDS README updated
- Your use case is not general. Shortcut methods like `package_with_versions` are for general purpose.

Additionally:
`YarnLock::Collection` is a just Array instance so you can iterate with various ruby method like:
`collection.group_by(&:package)` <- returns intended by you
I will update README with a comment of Array instance

**Pull request closed without merging**
